// File: ifid.v
// Generated by MyHDL 0.11
// Date: Sat Jan 23 20:55:49 2021


`timescale 1ns/10ps

module ifid (
    reset,
    instruction,
    ifid_reg,
    pc
);


input reset;
input [31:0] instruction;
output [63:0] ifid_reg;
reg [63:0] ifid_reg;
input [31:0] pc;




always @(reset, instruction, pc) begin: IFID_REG
    if ((reset == 1)) begin
        ifid_reg[32-1:0] = instruction;
        ifid_reg[64-1:32] = pc;
    end
end

endmodule
