// File: ifid.v
// Generated by MyHDL 0.11
// Date: Sat Jan 23 10:59:43 2021


`timescale 1ns/10ps

module ifid (
    reset,
    instruction,
    ifid_reg
);


input reset;
input [31:0] instruction;
output [31:0] ifid_reg;
reg [31:0] ifid_reg;




always @(instruction, reset) begin: IFID_REG
    if ((reset == 1)) begin
        ifid_reg = instruction;
    end
end

endmodule
