// File: pc_adder.v
// Generated by MyHDL 0.11
// Date: Sat Jan 23 20:55:49 2021


`timescale 1ns/10ps

module pc_adder (
    reset,
    clk,
    pc,
    pc_addr
);


input reset;
input [0:0] clk;
input [31:0] pc;
output [31:0] pc_addr;
reg [31:0] pc_addr;




always @(posedge clk) begin: PC_ADDER_PADDER
    if ((reset == 1)) begin
        pc_addr <= (pc + 1);
    end
end

endmodule
